appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fry9rJeWoPEjX9sSuLRBeBnyNo1S+JJM1tIK+pihKNWHYyg6Xb4esBv/m/nZdAdWPflnXeJOA8889BMi0jZx0KQhLYS/4nm+Yp/L829y0wuMHIa/p7Cj1bMh4bLs7JW2irFc0fh0/ckP801cWz0p8IJNe+jgzioewcdXedMs2z2BV+jeeeRJnWO7wkYaduZoyP7vFT+syDrsgPn78hv01/Sr4XKdvluN+z8OYWiJCdYSWSpXJGzrjXSzkg+t4QldzQ2rz/T+aS+v3nHC6cUdiiD/H+H7LKYykhgd7Km6dnnuKKIbYeiFwQGemWKSBIMjvCJBkL5PO8idrRxlN0ljH+P6DZgzbazxGYLbjcOPohXC67RsYcwyGTXdiQ9l24O1OnNZvL8bPmCC58rsv3gYBHwxdLlhKSCDfS5dWwQw818b4u7yoF1r9V5MtKuTfe6phVnw8/vEOQLathV2wReacQCgG6rhmviAzYjP+2dm+Z3mI3E33hHMXo/EDQ+XOjo/0sBtgrH/HNeFn3OjVzd5+RCa1A2nvY16UgdmjK/D9P15R+gQOFmxPNo934ZPPSPUy5wMSEnkLPOtbjos2ii1T9Dp7b72nvJRU5YTxEzJTO2GLzsjeQ6XUpy77KshL+LAQy1hxZ+yLJNJW4E9kIEUWeUuiXHRd62Oc65q4ga0LjU=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
